export const usersSeed = [
  {
    name: 'Store Administrator',
    email: 'admin@store.com',
    password: 'Admin@12345',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
    phone: '+8801700000001',
    addresses: [
      {
        label: 'Headquarters',
        street: '128 Gulshan Avenue, Tower 3',
        city: 'Dhaka',
        state: 'Dhaka Division',
        zip: '1212',
        country: 'Bangladesh',
        phone: '+8801700000001',
        isDefault: true,
      },
    ],
  },
  {
    name: 'Sarah Rahman',
    email: 'customer@store.com',
    password: 'Customer@12345',
    role: 'customer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    phone: '+8801800000002',
    addresses: [
      {
        label: 'Home',
        street: 'House 42, Road 11, Banani',
        city: 'Dhaka',
        state: 'Dhaka Division',
        zip: '1213',
        country: 'Bangladesh',
        phone: '+8801800000002',
        isDefault: true,
      },
    ],
  },
];

export const productsSeed = [
  {
    name: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    sku: 'AUDIO-SONY-XM5-BLK',
    shortDescription: 'Industry-leading noise cancellation with two processors and 8 microphones for unprecedented sound clarity.',
    description: 'The Sony WH-1000XM5 headphones rewrite the rules for distraction-free listening. Two processors control 8 microphones for unprecedented noise cancellation and exceptional call quality. With a newly developed driver, DSEE - Extreme and Hi-Res audio support, the WH-1000XM5 headphones provide awe-inspiring audio quality.',
    price: 399,
    discountPrice: 349,
    stock: 24,
    category: 'Audio',
    brand: 'Sony',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
        alt: 'Sony WH-1000XM5 Black Headphones',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800',
        alt: 'Sony WH-1000XM5 on Stand',
        isPrimary: false,
      },
    ],
    specs: [
      { key: 'Battery Life', value: 'Up to 30 hours with ANC on' },
      { key: 'Connectivity', value: 'Bluetooth 5.2 / 3.5mm Aux' },
      { key: 'Weight', value: '250 grams' },
      { key: 'Charging', value: 'USB-C Quick Charge (3 min = 3 hrs)' },
    ],
    ratingsAverage: 4.8,
    ratingsCount: 142,
    isFeatured: true,
    isTrending: true,
    metaTitle: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones | Best Price',
    metaDescription: 'Shop Sony WH-1000XM5 Wireless Noise Cancelling Headphones. Enjoy industry-leading ANC, 30-hour battery, and hi-res sound. Fast delivery.',
    keywords: ['Sony WH-1000XM5', 'Noise Cancelling Headphones', 'Wireless Audio', 'Bluetooth Headphones'],
  },
  {
    name: 'Apple AirPods Pro (2nd Generation) with USB-C MagSafe Case',
    sku: 'AUDIO-AAPL-APP2-WHT',
    shortDescription: 'Next-level Active Noise Cancellation, Adaptive Audio, Transparency mode, and Personalized Spatial Audio.',
    description: 'AirPods Pro (2nd generation) with USB-C deliver up to 2x more Active Noise Cancellation than the previous generation, with Transparency mode that enables you to hear the world around you, and all-new Adaptive Audio that dynamically tailors noise control to your environment.',
    price: 249,
    discountPrice: 219,
    stock: 35,
    category: 'Audio',
    brand: 'Apple',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800',
        alt: 'Apple AirPods Pro 2 in Charging Case',
        isPrimary: true,
      },
    ],
    specs: [
      { key: 'Chip', value: 'Apple H2 headphone chip' },
      { key: 'Battery Life', value: 'Up to 6 hours listening time per charge (30 hours with case)' },
      { key: 'Water Resistance', value: 'IP54 dust, sweat, and water resistant' },
      { key: 'Charging', value: 'USB-C, MagSafe, Apple Watch charger' },
    ],
    ratingsAverage: 4.9,
    ratingsCount: 230,
    isFeatured: true,
    isTrending: true,
    metaTitle: 'Apple AirPods Pro 2 USB-C | Genuine Wireless Earbuds',
    metaDescription: 'Buy authentic Apple AirPods Pro 2nd Gen with USB-C. Experience Spatial Audio, active noise cancellation, and all-day battery.',
    keywords: ['AirPods Pro 2', 'Apple Earbuds', 'ANC Earbuds', 'Spatial Audio'],
  },
  {
    name: 'Apple Watch Series 9 GPS 45mm Midnight Aluminum',
    sku: 'WEAR-AAPL-S9-45MID',
    shortDescription: 'S9 chip with Double Tap gesture, brighter display, on-device Siri, and advanced health sensors.',
    description: 'Apple Watch Series 9 helps you stay connected, active, healthy, and safe. Featuring the S9 SiP, an ultra-bright display, the magical new Double Tap gesture to interact without touching the screen, and Precision Finding for iPhone.',
    price: 429,
    discountPrice: 389,
    stock: 18,
    category: 'Wearables',
    brand: 'Apple',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
        alt: 'Apple Watch Series 9 Midnight',
        isPrimary: true,
      },
    ],
    specs: [
      { key: 'Display', value: 'Always-On Retina OLED up to 2000 nits' },
      { key: 'Sensors', value: 'Blood Oxygen, ECG, Temperature sensing' },
      { key: 'Battery', value: 'Up to 18 hours (36 hours in Low Power Mode)' },
      { key: 'Case Size', value: '45mm Aluminum' },
    ],
    ratingsAverage: 4.7,
    ratingsCount: 88,
    isFeatured: true,
    isTrending: false,
    metaTitle: 'Apple Watch Series 9 45mm Midnight GPS | Smartwatch',
    metaDescription: 'Order Apple Watch Series 9 GPS 45mm Midnight Aluminum. Features S9 chip, Double Tap gesture, and vital health monitoring.',
    keywords: ['Apple Watch Series 9', 'Smartwatch', 'Fitness Tracker', 'Health Watch'],
  },
  {
    name: 'Garmin Forerunner 265 GPS Running Smartwatch',
    sku: 'WEAR-GRMN-FR265-AQU',
    shortDescription: 'Brilliant AMOLED touchscreen display with training readiness, heart rate variability, and morning reports.',
    description: 'Tune in to your body with the Garmin Forerunner 265 GPS running smartwatch. Its colorful AMOLED touchscreen display shines bright while battery life lasts up to 13 days in smartwatch mode. Morning report provides sleep analysis, recovery outlook, and daily training recommendations.',
    price: 449,
    discountPrice: null,
    stock: 12,
    category: 'Wearables',
    brand: 'Garmin',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800',
        alt: 'Garmin Forerunner Running Watch',
        isPrimary: true,
      },
    ],
    specs: [
      { key: 'Display', value: '1.3 inch AMOLED Touchscreen' },
      { key: 'Battery Life', value: 'Up to 13 days in smartwatch mode / 20 hours GPS' },
      { key: 'Water Rating', value: '5 ATM (50 meters)' },
      { key: 'Sensors', value: 'Multi-band GPS, Wrist Heart Rate, Pulse Ox' },
    ],
    ratingsAverage: 4.9,
    ratingsCount: 54,
    isFeatured: false,
    isTrending: true,
    metaTitle: 'Garmin Forerunner 265 Running Smartwatch AMOLED',
    metaDescription: 'Get the Garmin Forerunner 265 smartwatch with AMOLED display, advanced running metrics, and battery life up to 13 days.',
    keywords: ['Garmin Forerunner 265', 'Running Watch', 'AMOLED GPS Watch', 'Garmin Sports'],
  },
  {
    name: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard',
    sku: 'COMP-KEYC-Q1PRO-RGB',
    shortDescription: 'Full aluminum 75% QMK/VIA wireless mechanical keyboard with double-gasket design and hot-swappable switches.',
    description: 'The Keychron Q1 Pro is a groundbreaking full metal wireless custom mechanical keyboard. With our signature double-gasket design, all-aluminum CNC machined body, PBT keycaps, screw-in stabs, and wireless Bluetooth 5.1 connection, typing reaches sheer perfection.',
    price: 199,
    discountPrice: 179,
    stock: 15,
    category: 'Computing',
    brand: 'Keychron',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800',
        alt: 'Keychron Custom Mechanical Keyboard',
        isPrimary: true,
      },
    ],
    specs: [
      { key: 'Layout', value: '75% Exploded Layout' },
      { key: 'Body Material', value: 'Full CNC Machined Aluminum' },
      { key: 'Connectivity', value: 'Bluetooth 5.1 & Type-C Wired' },
      { key: 'Hot-swappable', value: 'Yes, 3-pin & 5-pin MX compatible' },
    ],
    ratingsAverage: 4.8,
    ratingsCount: 96,
    isFeatured: true,
    isTrending: false,
    metaTitle: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard',
    metaDescription: 'Shop Keychron Q1 Pro wireless custom mechanical keyboard. Aluminum frame, hot-swappable switches, QMK/VIA programmable.',
    keywords: ['Keychron Q1 Pro', 'Mechanical Keyboard', 'Custom Keyboard', 'Hot-swap Keyboard'],
  },
  {
    name: 'Logitech MX Master 3S Performance Wireless Ergonomic Mouse',
    sku: 'COMP-LOGI-MXM3S-GRY',
    shortDescription: 'Quiet click technology, 8K DPI track-on-glass sensor, and MagSpeed electromagnetic scrolling wheel.',
    description: 'Meet Logitech MX Master 3S — an iconic mouse remastered. Feel every moment of your workflow with even more precision, tactility, and performance, thanks to Quiet Clicks and an 8,000 DPI track-on-glass sensor. MagSpeed scrolling delivers 1,000 lines per second in near silence.',
    price: 109,
    discountPrice: 99,
    stock: 40,
    category: 'Computing',
    brand: 'Logitech',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800',
        alt: 'Logitech MX Master 3S Wireless Mouse',
        isPrimary: true,
      },
    ],
    specs: [
      { key: 'Sensor Resolution', value: '200 to 8000 DPI (set in increments of 50)' },
      { key: 'Battery', value: '500 mAh rechargeable Li-Po (up to 70 days)' },
      { key: 'Multi-Device', value: 'Connect up to 3 devices via Bluetooth/Bolt' },
      { key: 'Buttons', value: '7 programmable buttons + gesture button' },
    ],
    ratingsAverage: 4.9,
    ratingsCount: 310,
    isFeatured: true,
    isTrending: true,
    metaTitle: 'Logitech MX Master 3S Wireless Mouse | Ergonomic Performance',
    metaDescription: 'Buy Logitech MX Master 3S wireless mouse. 8K DPI sensor, quiet clicks, ergonomic grip, and MagSpeed electromagnetic wheel.',
    keywords: ['Logitech MX Master 3S', 'Ergonomic Mouse', 'Wireless Productivity Mouse', 'Logitech MX'],
  },
  {
    name: 'Sony Alpha 7 IV Full-Frame Mirrorless Camera Body',
    sku: 'PHOTO-SONY-A7M4-BODY',
    shortDescription: '33MP full-frame Exmor R CMOS sensor with 4K 60p 10-bit recording and real-time Eye AF for photo and video.',
    description: 'The Sony a7 IV is the ideal all-around hybrid camera, featuring a 33MP Exmor R back-illuminated CMOS sensor, BIONZ XR processing engine, 4K 60p video in 10-bit 4:2:2, 5-axis in-body image stabilization, and class-leading autofocus tracking.',
    price: 2499,
    discountPrice: 2299,
    stock: 5,
    category: 'Photography',
    brand: 'Sony',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800',
        alt: 'Sony A7 IV Mirrorless Camera',
        isPrimary: true,
      },
    ],
    specs: [
      { key: 'Megapixels', value: '33MP Full-Frame Exmor R Sensor' },
      { key: 'Video Resolution', value: '4K 60p 10-Bit 4:2:2 / FHD 120p' },
      { key: 'Autofocus', value: '759 phase-detection AF points with Real-Time Eye AF' },
      { key: 'Stabilization', value: '5-axis Optical In-Body Image Stabilization' },
    ],
    ratingsAverage: 4.9,
    ratingsCount: 42,
    isFeatured: false,
    isTrending: true,
    metaTitle: 'Sony Alpha 7 IV Full-Frame Mirrorless Camera Body',
    metaDescription: 'Shop Sony A7 IV full-frame mirrorless camera. 33MP sensor, 4K 60p video, 10-bit color, advanced autofocus for photo & video creators.',
    keywords: ['Sony A7 IV', 'Full-Frame Mirrorless', '4K Video Camera', 'Sony Alpha'],
  },
  {
    name: 'Bellroy Classic Backpack Plus 24L Laptop Pack',
    sku: 'LIFE-BELL-BP24-BLK',
    shortDescription: 'Refined dual-compartment backpack with dedicated 16-inch laptop pocket, Lumbar support, and weather-resistant fabric.',
    description: 'The Bellroy Classic Backpack Plus is designed for urban commuters and travelers who demand seamless organization. Features a separate work hub for your laptop and notebook, quick-access exterior pockets, contoured back padding, and durable recycled water-resistant fabric.',
    price: 189,
    discountPrice: 169,
    stock: 20,
    category: 'Lifestyle',
    brand: 'Bellroy',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800',
        alt: 'Bellroy Premium Backpack',
        isPrimary: true,
      },
    ],
    specs: [
      { key: 'Capacity', value: '24 Liters' },
      { key: 'Laptop Compartment', value: 'Fits up to 16 inch MacBook Pro' },
      { key: 'Material', value: 'Durable water-resistant recycled woven fabric' },
      { key: 'Warranty', value: 'Backed by Bellroy 3-year warranty' },
    ],
    ratingsAverage: 4.8,
    ratingsCount: 77,
    isFeatured: true,
    isTrending: false,
    metaTitle: 'Bellroy Classic Backpack Plus 24L | Water-Resistant Tech Bag',
    metaDescription: 'Buy Bellroy Classic Backpack Plus 24L. Holds a 16-inch laptop with ergonomic comfort and clean minimalist styling. Free shipping.',
    keywords: ['Bellroy Backpack', 'Laptop Backpack 24L', 'Urban Daypack', 'Tech Travel Bag'],
  },
];
